import json, os

def md(source): return {"cell_type":"markdown","metadata":{},"source":source}
def code(source, outputs=None): return {"cell_type":"code","execution_count":None,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":""},"outputs":outputs or [],"source":source}

# ─── Cell 1: Intro ────────────────────────────────────────────────────────────
c1 = md([
"# 🦺 Construction Safety Monitor - Complete Training Pipeline\n",
"\n",
"This notebook focuses on the Pose + ResNet architecture for the Construction Safety Monitor:\n",
"1. **Phase 2**: Generating pose-derived anatomical Ground Truth ROIs using `YOLOv8-Pose` to match inference behavior.\n",
"2. **Phase 3**: Training MobileNetV3 specific classification heads (`helmet`, `vest`, `gloves`, `boots`, `goggles`) over the realistic ROIs.\n",
"3. **Phase 4**: Visualizing end-to-end inference over a test image."
])

# ─── Cell 2: Dependencies ─────────────────────────────────────────────────────
c2 = code([
"!pip install ultralytics opencv-python-headless matplotlib seaborn pandas pillow pyyaml torch torchvision --quiet\n",
"\n",
"import ultralytics\n",
"from ultralytics import YOLO\n",
"ultralytics.checks()\n",
])

# ─── Cell 3: Setup Paths ──────────────────────────────────────────────────────
c3 = code([
"import os\n",
"from pathlib import Path\n",
"import yaml\n",
"\n",
"USE_DRIVE = False\n",
"\n",
"if USE_DRIVE:\n",
"    from google.colab import drive\n",
"    drive.mount('/content/drive')\n",
"    DATASET_ROOT = Path('/content/drive/MyDrive/YoloDataset')\n",
"else:\n",
"    DATASET_ROOT = Path('YoloDataset')\n",
"\n",
"assert DATASET_ROOT.exists(), f'Dataset not found at {DATASET_ROOT}'\n",
"print(f'Dataset found at: {DATASET_ROOT}')\n",
"\n",
"MODEL_DIR = Path('construction_safety/models')\n",
"MODEL_DIR.mkdir(parents=True, exist_ok=True)\n",
"\n",
"# Setup temporary absolute dataset path for YOLOv8 \n",
"DATA_YAML = Path('dataset_abs.yaml')\n",
"CLASS_NAMES = ['helmet','gloves','vest','boots','goggles','none','Person',\n",
"               'no_helmet','no_goggle','no_gloves','no_boots']\n",
"\n",
"dataset_config = {\n",
"    'path': str(DATASET_ROOT.resolve()),\n",
"    'train': 'images/train',\n",
"    'val':   'images/val',\n",
"    'test':  'images/test',\n",
"    'nc': 11,\n",
"    'names': {i: n for i, n in enumerate(CLASS_NAMES)},\n",
"}\n",
"\n",
"with open(DATA_YAML, 'w') as f:\n",
"    yaml.dump(dataset_config, f, default_flow_style=False)\n",
])

# ─── Cell 6: Phase 2 Markdown ─────────────────────────────────────────────────
c6 = md([
"## Phase 2: Pose-Based ROI Extractor\n",
"We use YOLOv8-pose to locate keypoints on each worker from our Ground Truth labels, deriving anatomical bounding boxes (Head, Torso, Wrists) and matching their IoU against actual Ground Truth target PPE boxes to label them realistically for classifiers."
])

# ─── Cell 7: Pose Extractor ───────────────────────────────────────────────────
c7 = code([
"import cv2\n",
"import numpy as np\n",
"import torch\n",
"from torch.utils.data import Dataset, DataLoader\n",
"from torchvision import transforms\n",
"\n",
"class BBox:\n",
"    def __init__(self, x1, y1, x2, y2):\n",
"        self.x1, self.y1, self.x2, self.y2 = x1, y1, x2, y2\n",
"        \n",
"def compute_iou(boxA, boxB):\n",
"    xA = max(boxA.x1, boxB.x1)\n",
"    yA = max(boxA.y1, boxB.y1)\n",
"    xB = min(boxA.x2, boxB.x2)\n",
"    yB = min(boxA.y2, boxB.y2)\n",
"    interArea = max(0, xB - xA) * max(0, yB - yA)\n",
"    if interArea == 0: return 0.0\n",
"    boxAArea = (boxA.x2 - boxA.x1) * (boxA.y2 - boxA.y1)\n",
"    boxBArea = (boxB.x2 - boxB.x1) * (boxB.y2 - boxB.y1)\n",
"    return interArea / float(boxAArea + boxBArea - interArea)\n",
"\n",
"class PoseROIBuilder:\n",
"    def __init__(self, dataset_dir, split='train', roi_type='helmet'):\n",
"        self.dataset_dir = Path(dataset_dir)\n",
"        self.roi_type = roi_type\n",
"        self.split = split\n",
"        self.pose_model = YOLO('yolov8n-pose.pt')\n",
"        self.samples = []\n",
"        self._build()\n",
"        \n",
"    def _build(self):\n",
"        print(f\"Building Pose-derived ROIs for {self.roi_type} [{self.split}]...\")\n",
"        PPE_CLASSES = {\n",
"            'helmet': {'present': 0, 'absent': 7},\n",
"            'vest':   {'present': 2, 'absent': None},\n",
"            'gloves': {'present': 1, 'absent': 9},\n",
"            'boots':  {'present': 3, 'absent': 10},\n",
"            'goggles':{'present': 4, 'absent': 8}\n",
"        }\n",
"        \n",
"        c_map = PPE_CLASSES.get(self.roi_type, {})\n",
"        present_cls = c_map.get('present')\n",
"        absent_cls = c_map.get('absent')\n",
"        \n",
"        img_dir = self.dataset_dir / 'images' / self.split\n",
"        lbl_dir = self.dataset_dir / 'labels' / self.split\n",
"        \n",
"        for img_path in list(img_dir.glob('*.jpg')):\n",
"            lbl_path = lbl_dir / img_path.with_suffix('.txt').name\n",
"            if not lbl_path.exists(): continue\n",
"            \n",
"            img = cv2.imread(str(img_path))\n",
"            if img is None: continue\n",
"            h, w = img.shape[:2]\n",
"            \n",
"            persons, present_boxes, absent_boxes = [], [], []\n",
"            for line in lbl_path.read_text().splitlines():\n",
"                parts = line.strip().split()\n",
"                if len(parts) < 5: continue\n",
"                cls_id = int(parts[0])\n",
"                cx, cy, bw, bh = (float(p) for p in parts[1:5])\n",
"                x1, y1 = (cx - bw/2)*w, (cy - bh/2)*h\n",
"                x2, y2 = (cx + bw/2)*w, (cy + bh/2)*h\n",
"                \n",
"                if cls_id == 6: persons.append(BBox(x1, y1, x2, y2))\n",
"                elif cls_id == present_cls: present_boxes.append(BBox(x1, y1, x2, y2))\n",
"                elif cls_id == absent_cls: absent_boxes.append(BBox(x1, y1, x2, y2))\n",
"                \n",
"            for pbox in persons:\n",
"                px1, py1, px2, py2 = int(max(0, pbox.x1)), int(max(0, pbox.y1)), int(min(w, pbox.x2)), int(min(h, pbox.y2))\n",
"                worker_crop = img[py1:py2, px1:px2]\n",
"                if worker_crop.size == 0: continue\n",
"                \n",
"                res = self.pose_model.predict(worker_crop, verbose=False, device='cpu')[0]\n",
"                if res.keypoints is None or len(res.keypoints.data) == 0: continue\n",
"                kp = res.keypoints.data[0].cpu().numpy()\n",
"                \n",
"                target_roi = None\n",
"                \n",
"                if self.roi_type == 'helmet':\n",
"                    head_kps = [k for k in kp[:5] if k[2] > 0.5]\n",
"                    if head_kps:\n",
"                        cx = np.mean([k[0] for k in head_kps]) + px1\n",
"                        cy = np.mean([k[1] for k in head_kps]) + py1\n",
"                        head_size = 40.0\n",
"                        if kp[5][2] > 0.5 and kp[6][2] > 0.5:\n",
"                            shoulder_width = abs(kp[6][0] - kp[5][0])\n",
"                            head_size = max(30.0, shoulder_width * 0.45)\n",
"                        \n",
"                        rx1 = cx - head_size * 1.4\n",
"                        rx2 = cx + head_size * 1.4\n",
"                        ry1 = cy - head_size * 2.2\n",
"                        ry2 = cy + head_size * 1.0\n",
"                        target_roi = BBox(rx1, ry1, rx2, ry2)\n",
"                        \n",
"                elif self.roi_type == 'vest':\n",
"                    l_sh, r_sh = kp[5], kp[6]\n",
"                    l_hip, r_hip = kp[11], kp[12]\n",
"                    if all(k[2] > 0.5 for k in [l_sh, r_sh, l_hip, r_hip]):\n",
"                        pad = 10\n",
"                        rx1 = min(l_sh[0], r_sh[0], l_hip[0], r_hip[0]) + px1 - pad\n",
"                        ry1 = min(l_sh[1], r_sh[1]) + py1 - pad\n",
"                        rx2 = max(l_sh[0], r_sh[0], l_hip[0], r_hip[0]) + px1 + pad\n",
"                        ry2 = max(l_hip[1], r_hip[1]) + py1 + pad\n",
"                        target_roi = BBox(rx1, ry1, rx2, ry2)\n",
"                        \n",
"                elif self.roi_type == 'gloves':\n",
"                    # Pick the highest confidence wrist\n",
"                    w_kp = kp[9] if kp[9][2] > kp[10][2] else kp[10]\n",
"                    if w_kp[2] > 0.5:\n",
"                        r = 30.0\n",
"                        target_roi = BBox(w_kp[0]+px1-r, w_kp[1]+py1-r, w_kp[0]+px1+r, w_kp[1]+py1+r)\n",
"                        \n",
"                elif self.roi_type == 'boots':\n",
"                    # Pick highest confidence ankle\n",
"                    a_kp = kp[15] if kp[15][2] > kp[16][2] else kp[16]\n",
"                    if a_kp[2] > 0.5:\n",
"                        bw, bhu, bhd = 35.0, 45.0, 20.0\n",
"                        target_roi = BBox(a_kp[0]+px1-bw, a_kp[1]+py1-bhu, a_kp[0]+px1+bw, a_kp[1]+py1+bhd)\n",
"                        \n",
"                elif self.roi_type == 'goggles':\n",
"                    eyes = [k for k in (kp[1], kp[2], kp[0]) if k[2] > 0.5]\n",
"                    if len(eyes) >= 1:\n",
"                        cx_eye = sum(k[0] for k in eyes) / len(eyes) + px1\n",
"                        cy_eye = sum(k[1] for k in eyes) / len(eyes) + py1\n",
"                        g_size = max(15.0, 24.0)\n",
"                        target_roi = BBox(cx_eye-g_size*1.5, cy_eye-g_size*0.8, cx_eye+g_size*1.5, cy_eye+g_size*1.2)\n",
"                        \n",
"                if target_roi is None: continue\n",
"                \n",
"                label = None\n",
"                for gt in present_boxes:\n",
"                    if compute_iou(target_roi, gt) > 0.05:\n",
"                        label = 2; break\n",
"                if label is None:\n",
"                    for gt in absent_boxes:\n",
"                        if compute_iou(target_roi, gt) > 0.05:\n",
"                            label = 0; break\n",
"                            \n",
"                if label is None and absent_cls is None:\n",
"                    label = 0  # Default to absent for vest/harness since no bounding box exists\n",
"                elif label is None:\n",
"                    continue\n",
"                \n",
"                tx1, ty1 = int(max(0, target_roi.x1)), int(max(0, target_roi.y1))\n",
"                tx2, ty2 = int(min(w, target_roi.x2)), int(min(h, target_roi.y2))\n",
"                \n",
"                roi_img = img[ty1:ty2, tx1:tx2]\n",
"                if roi_img.size > 0:\n",
"                    self.samples.append((roi_img, label))\n",
"                    \n",
"        print(f\"  → Extracted {len(self.samples)} valid samples for {self.roi_type}.\")\n",
"        \n",
"    def __len__(self): return len(self.samples)\n",
"    def __getitem__(self, idx):\n",
"        return self.samples[idx][0], self.samples[idx][1]"
])

# ─── Cell 8: Phase 3 Markdown ─────────────────────────────────────────────────
c8 = md([
"## Phase 3: Train ResNet Head Classifiers\n",
"We extract realistically scaled training/validation sets through the Pose Builder for each class, and loop through training each individualized ResNet-18 classifier."
])

# ─── Cell 9: ResNet Training ──────────────────────────────────────────────────
c9 = code([
"import torch.nn as nn\n",
"import torch.optim as optim\n",
"from torchvision.models import mobilenet_v3_small\n",
"\n",
"class TorchCropDataset(Dataset):\n",
"    def __init__(self, base_ds, transform=None):\n",
"        self.base_ds = base_ds\n",
"        self.transform = transform\n",
"        \n",
"    def __len__(self): return len(self.base_ds)\n",
"    def __getitem__(self, idx):\n",
"        img, label = self.base_ds[idx]\n",
"        rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
"        if self.transform:\n",
"            rgb = self.transform(rgb)\n",
"        return rgb, torch.tensor(label, dtype=torch.long)\n",
"\n",
"def train_head(head_name):\n",
"    print(f\"\\n{'='*50}\\nTraining {head_name.upper()} Head classifier\\n{'='*50}\")\n",
"    train_ds = PoseROIBuilder(DATASET_ROOT, split='train', roi_type=head_name)\n",
"    val_ds = PoseROIBuilder(DATASET_ROOT, split='val', roi_type=head_name)\n",
"    \n",
"    if len(train_ds) == 0:\n",
"        print(f\"No samples for {head_name}, skipping.\")\n",
"        return\n",
"\n",
"    transform = transforms.Compose([\n",
"        transforms.ToPILImage(),\n",
"        transforms.Resize((224, 224)),\n",
"        transforms.RandomHorizontalFlip(),\n",
"        transforms.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.2),\n",
"        transforms.ToTensor(),\n",
"        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n",
"    ])\n",
"    \n",
"    val_transform = transforms.Compose([\n",
"        transforms.ToPILImage(),\n",
"        transforms.Resize((224, 224)),\n",
"        transforms.ToTensor(),\n",
"        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n",
"    ])\n",
"    \n",
"    train_loader = DataLoader(TorchCropDataset(train_ds, transform), batch_size=32, shuffle=True)\n",
"    val_loader = DataLoader(TorchCropDataset(val_ds, val_transform), batch_size=32, shuffle=False)\n",
"    \n",
"    device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
"    model = mobilenet_v3_small(weights='IMAGENET1K_V1')\n",
"    in_features = model.classifier[3].in_features\n",
"    model.classifier[3] = nn.Linear(in_features, 3)\n",
"    model = model.to(device)\n",
"    \n",
"    optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)\n",
"    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=30)\n",
"    criterion = nn.CrossEntropyLoss()\n",
"    \n",
"    best_val_acc = 0.0\n",
"    epochs = 30\n",
"    \n",
"    for epoch in range(1, epochs + 1):\n",
"        model.train()\n",
"        total_loss = 0.0\n",
"        for imgs, labels in train_loader:\n",
"            imgs, labels = imgs.to(device), labels.to(device)\n",
"            optimizer.zero_grad()\n",
"            out = model(imgs)\n",
"            loss = criterion(out, labels)\n",
"            loss.backward()\n",
"            optimizer.step()\n",
"            total_loss += loss.item()\n",
"            \n",
"        scheduler.step()\n",
"        \n",
"        model.eval()\n",
"        correct, total = 0, 0\n",
"        with torch.no_grad():\n",
"            for imgs, labels in val_loader:\n",
"                imgs, labels = imgs.to(device), labels.to(device)\n",
"                preds = model(imgs).argmax(dim=1)\n",
"                correct += (preds == labels).sum().item()\n",
"                total += len(labels)\n",
"                \n",
"        val_acc = correct / total if total > 0 else 0.0\n",
"        avg_loss = total_loss / len(train_loader)\n",
"        \n",
"        if epoch % 5 == 0 or epoch == 1:\n",
"            print(f\"  Epoch {epoch:2d}/{epochs} | Loss: {avg_loss:.4f} | Val Acc: {val_acc:.4f}\")\n",
"            \n",
"        if val_acc > best_val_acc:\n",
"            best_val_acc = val_acc\n",
"            torch.save(model.state_dict(), MODEL_DIR / f\"{head_name}_head.pth\")\n",
"            \n",
"    print(f\"Completed {head_name.upper()}. Best Val Acc: {best_val_acc:.4f}\")\n",
"\n",
"# Run training for all PPE class heads\n",
"for head in ['helmet', 'vest', 'gloves', 'boots', 'goggles']:\n",
"    train_head(head)\n",
"\n",
"print(\"\\nAll Training Phases Completed Successfully!\")"
])

# ─── Cell 10: Phase 4 Markdown ────────────────────────────────────────────────
c10 = md([
"## Phase 4: Full Pipeline Inference Visualization\n",
"In this final step, we execute a comprehensive end-to-end visualization of the system on a test image:\n",
"1. Compute YOLOv8-Pose to identify Workers and 17 COCO Keypoints.\n",
"2. Mathematically map precise regions (helmet, vest, gloves, boots, goggles) over the image.\n",
"3. Evaluate those mapped crops individually against the MobileNetV3-Small `.pth` files generated in Phase 3.\n",
"4. Render the safety statuses prominently on screen."
])

# ─── Cell 11: Inference Visualizer ────────────────────────────────────────────
c11 = code([
"import random\n",
"import matplotlib.patches as patches\n",
"from PIL import Image\n",
"import torchvision.transforms as T\n",
"import torch.nn.functional as F\n",
"\n",
"print(\"Loading MobileNet Classifiers...\")\n",
"heads = ['helmet', 'vest', 'gloves', 'boots', 'goggles']\n",
"models = {}\n",
"for h in heads:\n",
"    m = mobilenet_v3_small(weights=None)\n",
"    in_features = m.classifier[3].in_features\n",
"    m.classifier[3] = nn.Linear(in_features, 3)\n",
"    pth = MODEL_DIR / f'{h}_head.pth'\n",
"    if pth.exists():\n",
"        m.load_state_dict(torch.load(pth, map_location=device))\n",
"    m.to(device).eval()\n",
"    models[h] = m\n",
"\n",
"pose_model = YOLO('yolov8n-pose.pt')\n",
"val_imgs = list((DATASET_ROOT / 'images' / 'test').glob('*.jpg'))\n",
"if not val_imgs:\n",
"    val_imgs = list((DATASET_ROOT / 'images' / 'train').glob('*.jpg'))\n",
"if not val_imgs:\n",
"    print(\"No images found for inference test.\")\n",
"else:\n",
"    test_img = random.choice(val_imgs)\n",
"    img = cv2.imread(str(test_img))\n",
"    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
"    h, w = img.shape[:2]\n",
"    \n",
"    results = pose_model.predict(img, verbose=False, device='cpu')[0]\n",
"    \n",
"    fig, ax = plt.subplots(1, 1, figsize=(14, 12))\n",
"    ax.imshow(img_rgb)\n",
"    ax.axis('off')\n",
"    ax.set_title(\"End-to-End Inference: Pose Discovery + MobileNetV3 Assessment\", fontsize=16, fontweight='bold')\n",
"    \n",
"    if results.boxes is not None and len(results.boxes) > 0:\n",
"        for i, box in enumerate(results.boxes):\n",
"            # Draw Worker box\n",
"            x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()\n",
"            rect = patches.Rectangle((x1, y1), x2-x1, y2-y1, linewidth=3, edgecolor='yellow', facecolor='none')\n",
"            ax.add_patch(rect)\n",
"            ax.text(x1, max(0, y1-10), 'Worker', color='black', backgroundcolor='yellow', fontsize=12, weight='bold')\n",
"            \n",
"            if results.keypoints is not None and len(results.keypoints) > i:\n",
"                kp = results.keypoints.data[i].cpu().numpy()\n",
"                for k in kp:\n",
"                    if k[2] > 0.5:\n",
"                        ax.plot(k[0], k[1], 'o', color='cyan', markersize=4)\n",
"                \n",
"                rois = {}\n",
"                \n",
"                # Helmet\n",
"                head_kps = [k for k in kp[:5] if k[2] > 0.5]\n",
"                if head_kps:\n",
"                    cx, cy = np.mean([k[0] for k in head_kps]), np.mean([k[1] for k in head_kps])\n",
"                    h_sz = max(30.0, abs(kp[6][0] - kp[5][0]) * 0.45) if kp[5][2] > 0.5 and kp[6][2] > 0.5 else 40.0\n",
"                    rois['helmet'] = [cx-h_sz*1.4, cy-h_sz*2.2, cx+h_sz*1.4, cy+h_sz*1.0]\n",
"                \n",
"                # Vest\n",
"                if all(k[2] > 0.5 for k in [kp[5], kp[6], kp[11], kp[12]]):\n",
"                    pad = 10\n",
"                    rois['vest'] = [min(kp[5][0], kp[6][0], kp[11][0], kp[12][0])-pad, min(kp[5][1], kp[6][1])-pad, max(kp[5][0], kp[6][0], kp[11][0], kp[12][0])+pad, max(kp[11][1], kp[12][1])+pad]\n",
"                \n",
"                # Gloves\n",
"                wk = kp[9] if kp[9][2] > kp[10][2] else kp[10]\n",
"                if wk[2] > 0.5: rois['gloves'] = [wk[0]-30, wk[1]-30, wk[0]+30, wk[1]+30]\n",
"                \n",
"                # Boots\n",
"                ak = kp[15] if kp[15][2] > kp[16][2] else kp[16]\n",
"                if ak[2] > 0.5: rois['boots'] = [ak[0]-35, ak[1]-45, ak[0]+35, ak[1]+20]\n",
"                \n",
"                # Goggles\n",
"                eyes = [k for k in (kp[1], kp[2], kp[0]) if k[2] > 0.5]\n",
"                if len(eyes) >= 1:\n",
"                    cxe, cye = sum(k[0] for k in eyes) / len(eyes), sum(k[1] for k in eyes) / len(eyes)\n",
"                    gsz = max(15.0, 24.0)\n",
"                    rois['goggles'] = [cxe-gsz*1.5, cye-gsz*0.8, cxe+gsz*1.5, cye+gsz*1.2]\n",
"                \n",
"                val_transform = transforms.Compose([ transforms.ToPILImage(), transforms.Resize((224,224)), transforms.ToTensor(), transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225]) ])\n",
"                y_off = 10\n",
"                for h_name, roi in rois.items():\n",
"                    rx1, ry1, rx2, ry2 = max(0, int(roi[0])), max(0, int(roi[1])), min(w, int(roi[2])), min(h, int(roi[3]))\n",
"                    if rx2 <= rx1 or ry2 <= ry1: continue\n",
"                    \n",
"                    ax.add_patch(patches.Rectangle((rx1, ry1), rx2-rx1, ry2-ry1, linewidth=1.5, edgecolor='blue', linestyle='--', facecolor='none'))\n",
"                    \n",
"                    crop = img_rgb[ry1:ry2, rx1:rx2]\n",
"                    if crop.size > 0:\n",
"                        img_t = val_transform(crop).unsqueeze(0).to(device)\n",
"                        out = models[h_name](img_t)\n",
"                        pred_idx = out.argmax(dim=1).item()\n",
"                        stat = 'Present' if pred_idx == 2 else 'Absent'\n",
"                        col = 'lime' if pred_idx == 2 else 'red'\n",
"                        \n",
"                        # If model isn't trained (random weights), it's just defaulting, but visualization proves crops work.\n",
"                        ax.text(x2 + 10, max(0, y1 + y_off), f'{h_name.upper()}: {stat}', color=col, fontsize=12, weight='bold', bbox=dict(facecolor='black', alpha=0.7, edgecolor='none', pad=3))\n",
"                        y_off += 30\n",
"    plt.show()"
])

notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "accelerator": "GPU",
        "colab": {"gpuType": "T4", "provenance": []},
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}
    },
    "cells": [c1, c2, c3, c6, c7, c8, c9, c10, c11]
}

out_path = r"d:\Construction\train.ipynb"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print(f"Notebook written: {out_path}")
